FROM node:18-alpine

WORKDIR /var/www/html

# Copiar package.json primeiro
COPY package*.json ./

# Instalar dependências
RUN npm install

# Expor porta do Vite
EXPOSE 5173

# Comando padrão será sobrescrito pelo docker-compose
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
