version: '3.8'

services:
    laravel.test:
        build:
            context: .
            dockerfile: Dockerfile
        image: studyez-app:latest
        environment:
            WWWUSER: '1000'
            LARAVEL_SAIL: 1
        volumes:
            # Volume para compartilhar arquivos estáticos com nginx
            - 'app-public:/var/www/html/public'
            # Volume para compartilhar storage (fotos de perfil)
            - 'app-storage:/var/www/html/storage/app/public'
        networks:
            - sail
        depends_on:
            - mysql

    nginx:
        image: 'nginx:alpine'
        ports:
            - '8000:80'
        volumes:
            # Usar os volumes compartilhados
            - 'app-public:/var/www/html/public:ro'
            - 'app-storage:/var/www/html/storage/app/public:ro'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        networks:
            - sail
        depends_on:
            - laravel.test

    mysql:
        image: 'mysql:8.0'
        platform: linux/amd64
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_DATABASE: 'bancostudy'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail

    redis:
        image: 'redis:alpine'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '8025:8025'
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    app-public:
        driver: local
    app-storage:
        driver: local